Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/DTO/PersistentDTO/PlanDTO.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/EmptyLabeledCollectionView.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanCollectionViewCell.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanViewModel.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanLocalRepository.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanRepository.swift
Doesaegim/Doesaegim/Utility/CoreDataError.swift
Doesaegim/Doesaegim/Utility/Extensions/NSObject+Name.swift
Doesaegim/Doesaegim/Utility/Extensions/UIViewController+PresentAlert.swift
Doesaegim/NSManagedObjectClass/Plan+CoreDataClass.swift

> 변경사항 간략하게 
- resolves #13 
- 코어데이터로부터 저장된 데이터를 받아오도록 구현했습니다. 
- 체크박스를 토글해서 완료여부를 표시할 수 있도록 구현했습니다. 
- 코어데이터로부터 변경사항을 받아오거나 저장하는 데 실패하는 경우 알림을 띄우도록 했습니다.
> 고민, 과정, 궁금한점
- 댓글로 달겠습니다!

[일정 목록] 코어데이터와 일정 목록 연동 #13

---

Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanLocalRepository.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanRepository.swift
Doesaegim/Doesaegim/Utility/CoreDataError.swift

> 변경사항 간략하게 
- resolves #21 
- 재훈님이 알려주신대로 listConfiguration을 활용해서 삭제 기능을 구현했습니다. 
- 보경님이 CoreDataError가 Error를 채택하도록 하는 게 어떻냐고 추천해주셔서 이를 반영했습니다. 
> 고민, 과정, 궁금한점

[일정 목록] 일정 삭제 #21

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Utility/Extensions/UIViewController+SetRightBarPlusButton.swift

feat: 일정 추가 버튼 구현

---

Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/ViewModel/TravelListViewModel.swift

feat: 다시 불러오기

---

Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewController.swift

fix: 여행 추가 안되는 오류 해결

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationViewControllerDelegate.swift

- 장소 검색 화면에서 선택한 장소 정보를 LocationDTO 형태로 일정 추가 화면으로 보내는 작업을 구현했습니다.
- 일정 추가 화면에서는 장소 정보를 받아 장소 검색 버튼의 타이틀로 표시하도록 구현했습니다!
- resolves #22 
아래 댓글로 표시하겠습니다!
https://user-images.githubusercontent.com/50136980/202668882-5c28af9b-7b66-4bea-ba7d-87aaae62ff48.mp4

[장소 추가] 장소 검색 화면에서 선택한 장소를 일정 추가화면으로 보내도록 구현

---

Doesaegim/Doesaegim/Services/PersistentManager.swift

refactor: PersistentManager의 메서드들 리턴 값 Result 타입으로 변경

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ViewModel/ExpenseTravelViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanCollectionViewCell.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/ViewModel/TravelListViewModel.swift
Doesaegim/Doesaegim/Repository/PersistentStorage/PersistentRepository.swift
Doesaegim/Doesaegim/Repository/PersistentStorage/PersistentRepositoryProtocol.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanLocalRepository.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanRepository.swift
Doesaegim/Doesaegim/Utility/CoreDataError.swift
Doesaegim/Doesaegim/Utility/Errors.swift

> 변경사항 간략하게 
- 여행 목록, 일정 목록에서 코어데이터 호출, 저장 관련 메서드 리팩토링
- CoreDataErrorEntityType별로 세분화
- 여행 목록에서 여행 삭제 시 UI 업데이트 안되던 문제 해결
> 고민, 과정, 궁금한점

refactor: PersistentManager의 메서드들 리턴 타입 변경에 따른 리팩토링

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/ViewModel/ExpenseInfoViewModel.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ExpenseListViewModelProtocol.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseCollectionHeaderView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListCell.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseSectionHeaderView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ExpenseTravelViewModelProtocol.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListCell.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ViewModel/ExpenseTravelViewModel.swift
Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
Doesaegim/Doesaegim/Utility/Extensions/Int/Int+convertCostString.swift
Doesaegim/Doesaegim/Utility/Extensions/UIView+Frame.swift
Doesaegim/NSManagedObjectClass/Expense+CoreDataClass.swift

> 변경사항 간략하게 
> 고민, 과정, 궁금한점
<p>
</p>

[지출 목록] 지출목록 셀 디자인, 사용금액 표시

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift

> 변경사항 간략하게 
* 지출 추가 화면 UI만 구현을 헸습니다.
> 고민, 과정, 궁금한점
* ViewController 파일에 UI를 그리다보니깐 UI 관련 프로퍼티가 많아서 뷰컨트롤러 파일이 너무 커져서 선경님이 저번에 코멘트로 달아주신 `loadView` 메서드를 사용해봤습니다.
* `loadView`에서 사용할 뷰를 rootView로 넣어줬는데, 이 rootView에 작성한 UI프로퍼티에 접근해야하기 때문에 ex) rootView.addButton.addTarget ....
*  private 키워드를 붙이면 안될 것 같은데 뷰컨트롤러 파일이 커져도 뷰컨트롤러에 UI 프로퍼티 작성 및 Constraint 설정을 해주는게 더 나을까요..?!

[지출 추가] 지출 추가 UI 구현

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/PlaceSearchButton.swift

> 변경사항 간략하게 
- resolves #77 
- 다이어리 작성 화면 UI를 구현했습니다. 
- 장소검색 버튼 민석님이 전에 작성해주신 코드를 사용해서 PlaceSearchButton 객체로 분리해주었습니다. 
- 컨트롤러와 연결해서 뷰 뜨는 것까지 확인했습니다. 
> 고민, 과정, 궁금한점
- 스크럼에서도 말씀드린대로 이미지 슬라이더를 스크롤뷰를 쓸 지 컬렉션 뷰를 쓸 지 고민했는데요, 찾아봤을 때 컬렉션 뷰가 메모리 측면에서 좀 더 효율적이라는 내용을 봤고 또 사진 선택 해제 시에 이를 UI에 나타낼 때 컬렉션 뷰가 더 쉬울 것 같아서 컬렉션 뷰로 구현했습니다!

[다이어리 작성] UI 구현 #77

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/Model/ExchangeResponse.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/ExpenseAddPickerViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewController.swift
Doesaegim/Doesaegim/Utility/Constants.swift
Doesaegim/Doesaegim/Utility/Exchange/ExchangeDiskCache.swift
Doesaegim/Doesaegim/Utility/Exchange/ExchangeMemoryCache.swift

* UserDefault에 환율 정보를 담아두었는데 FileManager에 환율 정보를 저장하도록 변경하였습니다.
* UserDefault에 [날짜: 환율정보]를 인코딩해서 넣어줬는데, 날짜 넣도록 변경하였습니다.
* FileManager를 사용해 디스크 캐시를 구현하였습니다.
* NSCache를 사용해 메모리 캐시를 구현하였습니다.
* 디스크 캐시를 먼저 구현했는데, 하다보니깐 메모리 캐시도 구현해보면 좋을 것 같아서 메모리캐시도 구현을 했습니다.
* 굳이 메모리캐시까지 구현했나..? 라는 생각도 조금은 드네요..

[지출 추가] 환율 정보 캐시 구현

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/DTO/PersistentDTO/DiaryDTO.swift
Doesaegim/Doesaegim/Data/DTO/TemporaryDiary.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/TranslucentActivityIndicatorView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModelDelegate.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift
Doesaegim/Doesaegim/Repository/DiaryScene/DiaryDetail/DiaryDetailLocalRepository.swift
Doesaegim/Doesaegim/Repository/DiaryScene/DiaryDetail/DiaryDetailRepository.swift
Doesaegim/Doesaegim/Services/FileProcessManager.swift
Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift

> 변경사항 간략하게 
- resolves #68 
- 저장 기능을 구현했습니다 
> 고민, 과정, 궁금한점
- 오늘 스크럼 때 말씀드렸다시피 비동기 + 병렬 처리를 하고 싶어서 무수한 삽질을 했습니다...나중에 포스팅 쓰면 홍보하겠습니다...
영상 재생 왜 안될까요... 
슬랙으로 보내겠습니다... 
https://user-images.githubusercontent.com/81314063/204468126-b01d8adf-87f0-4652-9f41-499716743fe6.mp4
https://user-images.githubusercontent.com/81314063/204471572-c56c9e73-318c-4db1-aa39-c91e3c395137.mov

[다이어리 작성] 저장 기능 구현 #68

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/App/Info.plist
Doesaegim/Doesaegim/Presentation/SettingScene/SettingViewController.swift
Doesaegim/Doesaegim/Services/ShareManager.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendar.swift

* 인스타그램 스토리로 공유하기 기능을 구현하였습니다.
* 네이티브 기본 공유하기 기능을 구현하였습니다.
* 인스타로 공유하는 기능이 딥링크와 관련된 것이라고 확정을 한 상태로 딥링크에 대해 알아보다가, iOS에서는 유니버셜링크라고 딥링크의 한 종류를 사용한다는 것을 알았습니다.
* 유니버셜링크를 사용하려면 개발자 계정이 필수이고, 또한 웹서버도 구현해야된다고 해서 heroku로 간단하게 구현할 수 있다고해서 어찌저찌 해보다가.. 이건 아닌 것 같아서 다시 찾아보다보니깐 인스타그램 API에서 스토리로 공유하는 기능이 있어서 공식문서와 블로그를 보고 구현했습니다.
* 피드로 공유하는 기능도 있는데, 유니버셜링크가 필요하다고 그래서.. 일단 패스 했습니다.
* 인스타그램을 안하는 유저도 있기때문에, iOS 네이티브 공유하는 기능을 구현했습니다.
|인스타그램 스토리|아이폰 기본|
|---|---|
|![ezgif com-gif-maker](https://user-images.githubusercontent.com/77199797/204483556-175f153f-76ad-47ea-af40-51deb91a1e16.gif)|![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/77199797/204484035-2ccb4641-8111-4ad8-81a1-eb9b87aa2a3f.gif)|

[공유하기] 이미지 공유 기능 구현

---

Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
Doesaegim/Doesaegim/Utility/Extensions/UIViewController+PresentAlert.swift

* UIViewController Extension으로 여러개의 Action이 있는 Alert을 띄우는 메서드를 구현했습니다.
* 추가화면에서 작성한 내용이 1개라도 있으면 뒤로가기 버튼을 눌렀을 때,  Alert이 뜨도록 구현했습니다. #8 
* 작성한 항목이 있는지 ViewModel에 전달해서 뷰모델에서 판별하는데 파라미터 값이 너무 많아서 이게 맞나..? 싶었습니다. 혹시 더 좋은 구현 방식이 있으면 공유 부탁드립니다..!

[추가 화면] 추가하는 화면에 기능 추가

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationViewController.swift
Doesaegim/Doesaegim/Utility/Extensions/Array+SafeIndex.swift

> 변경사항 간략하게 
- Array에 safe index subscript를 추가했습니다. 

refactor: safe index subscript 적용

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/DTO/PersistentDTO/PlanDTO.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddView.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanAdd/PlanAddLocalRepository.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanAdd/PlanAddRepository.swift
Doesaegim/Doesaegim/Utility/Custom/AddViewComponents/AddViewCompleteButton.swift
Doesaegim/Doesaegim/Utility/Custom/AddViewComponents/AddViewInputButton.swift

* loadView를 사용해 UI를 불러오도록 구현하였습니다.
* Repository 추가하였습니다.
* 재사용되는 뷰를 분리하였습니다.
* ViewController의 역할을 줄이고 ViewModel이 할 수 있도록 변경하였습니다.
* 일정 추가 뷰가 메모리에서 해제될 때, 등록된 옵저버를 삭제해줬습니다.
* loadView로 제거하니깐 ViewController 코드가 줄어들고, UI 관련한 것들을 View 파일에서 한눈에 확인할 수 있어서 좋네요!

[일정 추가] 일정 추가 관련 리팩토링

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/ViewModel/TravelDiaryViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/DiaryListViewModelProtocol.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift

> 변경사항 간략하게 
이전의 리뷰를 반영하고 튜플 형태에서 구조체로 데이터를 전달하였습니다.
> 고민, 과정, 궁금한점

[리팩토링] 다이어리 리스트 튜플에서 구조체로 변경

---

Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanCollectionViewCell.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
Doesaegim/NSManagedObjectClass/Plan+CoreDataClass.swift

> 변경사항 간략하게 
- 일정목록 배경 색상을 변경했습니다.
- 원래부터 .white였는데 왜 반영이 안될까 해서 봤더니 listConfiguration에서 설정해줘야했습니다ㅠ 
- 일정목록 뷰모델에 있던 dateFormat 관련 코드를 Date extension으로 옮겨주었습니다. 
- 저번에 멘토님이 통일하면 좋을 것 같다고 하셨어서 통일해주었습니다. 
- 일정 저장 시 장소 정보가 누락되고 있어서 장소도 저장되도록 변경했습니다. 
- 일정 셀 날짜, 장소, 설명 글자 색상을 변경했습니다. 
- figma에서는 grey2였는데 조금 흐릿해보여서 grey3으로 교체했습니다..!
> 고민, 과정, 궁금한점

[일정 목록] 리팩토링

---

Doesaegim/Doesaegim/App/Assets.xcassets/ColorSets/calendarOrange.colorset/Contents.json
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CalendarProtocol.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CalendarViewController.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendar.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCell.swift
Doesaegim/Doesaegim/Utility/Extensions/UIColor+.swift

* 멀티터치 되는 캘린더의 경우 출발 날짜와 도착 날짜 사이 기간을 표시해두도록 UI를 수정하였습니다.
* 날짜를 터치하면 delegate로 날짜를 Date 자료형으로 전달하도록 수정하였습니다.
* 회의 때 말씀드렸던 것 처럼 일요일 관련 이슈가 해결된 것 처럼 보여서 오늘은 해결이 안될 것 같고.. 다시 문제가 발생해야 해결할 수 있을 것 같아요 ..😅

[커스텀 캘린더] 리팩토링 및 UI 개선

---

Doesaegim/Doesaegim/Data/DTO/TemporaryDiary.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModelDelegate.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/PickerDataSource.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift

> 변경사항 간략하게 
- 일정 목록, 다이어리 작성 관련 코드에 safeIndex를 반영했습니다. 
- 다이어리 작성 시 여행을 선택할 때 최초로 피커가 뜨면 최상단의 여행이 기본 선택값이 되도록 했습니다. 
- 안그러면 여행이 하나 밖에 없거나 첫번째 여행을 선택하고 싶을 때 일단 스크롤 해서 내렸다가 다시 올라와야돼서 귀찮더라구요...
- 하면서 weak 누락된 부분들 추가해주었습니당
- 다이어리 작성 시 유저가 직접 날짜를 선택할 수 있도록 했습니다.   
> 고민, 과정, 궁금한점

[다이어리 작성] 날짜 선택 기능 추가 및 리팩토링

---

Doesaegim/Doesaegim/Presentation/MainTabBarController.swift
Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/MapViewController.swift
Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/ViewModel/MapViewModel.swift

> 변경사항 간략하게 
- 작성했던 다이어리가 맵에 나타나지 않는 버그를 수정하였습니다.
- 맵에 진입했을 때, 가장 최근에 작성했던 다이어리의 어노테이션이 맵의 가운데 오도록 설정하였습니다.
- 다이어리가 없는 상태일 경우 맵의 중앙은 종로가 됩니다. 
- 탭바의 색상과 투명도를 설정하여, 맵에 진입한 후에도 탭바가 투명해지지 않도록 했습니다.
> 고민, 과정, 궁금한점
- mapView가 nil인 상태에서 어노테이션을 추가하는 메서드를 실행시키고 있었습니다.

[지도화면] 애노테이션이 나타나지 않는 버그 수정

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/ProgressiveImageCollectionViewCell.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModelDelegate.swift
Doesaegim/Doesaegim/Utility/Enum/ImageStatus.swift
Doesaegim/Doesaegim/Utility/Extensions/UIImage/UIImage+.swift
Doesaegim/Doesaegim/Utility/Extensions/UIImage/UIImage+SystemImages.swift

> 변경사항 간략하게 
- 여행 선택 피커 상단에 취소, 확인 버튼이 담긴 툴바를 추가했습니다. 
- 이미지 추가 버튼을 셀마다 갖게 하고, 이미지가 추가되면 제거 버튼으로 변하도록 했습니다.
- 기존에는 이미지 피커를 통해 새로운 이미지를 선택할 때마다 기존에 선택된 이미지가 제거되었으나 이를 유지하도록 했습니다. 
> 고민, 과정, 궁금한점
- 여행 피커 툴바 추가 
https://user-images.githubusercontent.com/81314063/206914418-e994d375-ef23-4239-b98a-0abebf6301e7.mp4

[다이어리 작성] 사용성 개선

---

Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift

> 변경사항 간략하게 
- 다이어리 상세 화면에서 장소가 옵셔널로 변경됨에 따라 장소값이 존재하지 않을 경우 히든 처리 되도록 수정했습니다.
- 다이어리의 날짜도 옵셔널로 처리되어 있어 장소값과 동일하게 처리했습니다.
- 설정화면에서 날짜 및 시간 표시 방식이 변경될 때마다 상세 화면에 표시될 date도 변경되도록 수정했습니다.
> 고민, 과정, 궁금한점
설정에 따라 날짜가 변경되는 모습입니다!
https://user-images.githubusercontent.com/50136980/206979856-fd779c69-224e-47f9-b4e7-5ac729ea3466.mp4

[다이어리 조회] 표시할 텍스트가 nil일 때 히든 처리 및 날짜 표시 설정 반영

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryEdit/View/DiaryEditViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryEdit/ViewModel/DiaryEditViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryEdit/ViewModel/DiaryEditViewModelDelegate.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryPhotoDetail/DiaryPhotoDetailViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController.swift
Doesaegim/Doesaegim/Repository/DiaryScene/DiaryEdit/DiaryEditLocalRepository.swift
Doesaegim/Doesaegim/Repository/DiaryScene/DiaryEdit/DiaryEditRepository.swift
Doesaegim/Doesaegim/Utility/Extensions/UIImage/UIImage+SystemImages.swift
Doesaegim/Doesaegim/Utility/Extensions/UIViewController+SetRightBarPlusButton.swift

> 변경사항 간략하게 
- 다이어리 편집 기능을 구현했습니다. 
- 아직 안 된 부분은 다이어리 제목을 내비게이션 바에서 레이블로 분리하기랑
- 여행을 변경하면 다이어리 날짜도 그 기한 안에 들어가도록 변경하는 작업입니다..!
- PR자체는 큰데 추가 화면과 거의 유사한 로직이라 변경한 부분만 보시기 편하게 코멘트 달아놓을게요!
- 다이어리 디테일부터는 탭바가 안 보이도록 변경했습니다. 
- 디테일 화면 -> 사진 화면, 사진 화면 -> 얼굴 인식 화면 으로 스와이프 시 배경이 이상한 문제를 해결했습니다. 
- 전자는 이미지 뷰 레이아웃 설정 + clipsToBounds 누락이 원인이었고
- 후자는 배경 색이 뒤늦게 설정되어 발생하는 문제였습니다. 
> 고민, 과정, 궁금한점
https://user-images.githubusercontent.com/81314063/207010174-59795b20-6d52-4dc0-8b0a-99b4a924e1ca.mp4

[다이어리] 버그 해결 및 편집 기능 추가 

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/DTO/PersistentDTO/PlanDTO.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddView.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanAdd/PlanAddLocalRepository.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanAdd/PlanAddRepository.swift
Doesaegim/NSManagedObjectClass/Plan+CoreDataClass.swift

* #164 #172 #166 
* 일정 상세화면을 구현하였습니다.
* 일정 수정 기능을 구현하였습니다.
* 일정 추가 및 수정 시, 장소는 옵셔널로 변경하였습니다.
* 일정을 수정할 때, 장소를 수정하면 크래시나는 오류를 수정하였습니다.
* 장소를 삭제할 수 있는 버튼을 구현하였습니다.
* 일정에 장소를 수정할 때, 그냥 수정만 해주면 될 줄 알았습니다..
* 장소가 없는 경우에 장소를 추가한 경우
* location 객체를 만들어서 일정에 넣어줍니다.
* 장소가 있는 경우 장소를 변경한 경우
* plan에 location 객체를 수정해줘야합니다.
* 장소가 있는 경우에 장소를 삭제한 경우
* plan에 location 객체를 nil
* 맨처음에는 무작정 plan.setValue(location~) 이런식으로 교체를 해줬었는데 앱이 터져서 원인을 찾아보다가 해결했습니다.
* 장소를 선택하면 삭제할 수가 없어서 장소를 지우는 버튼을 구현하였습니다.

[일정 디테일 및 수정] 일정 디테일 화면 및 수정 기능 구현

---

Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/PlaceSearchButton.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryEdit/View/DiaryEditViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryEdit/ViewModel/DiaryEditViewModel.swift
Doesaegim/Doesaegim/Repository/DiaryScene/DiaryEdit/DiaryEditLocalRepository.swift
Doesaegim/Doesaegim/Repository/DiaryScene/DiaryEdit/DiaryEditRepository.swift

> 변경사항 간략하게 
- 다이어리 작성, 편집 시 선택한 장소를 삭제하는 기능을 추가했습니다. 
> 고민, 과정, 궁금한점
- 다이어리 작성 시 장소 삭제 
https://user-images.githubusercontent.com/81314063/207214755-ff74f14b-5721-4522-ba78-a0107ec00dca.mp4
- 다이어리 편집 시 장소 삭제
https://user-images.githubusercontent.com/81314063/207214918-2c3bbeef-b0a1-40c6-a212-5a8e3bc51089.mp4

[다이어리 작성, 편집] 장소 삭제 기능 추가 

---

Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModelDelegate.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelCollectionViewCell.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift

> 변경사항 간략하게 
- 여행과 다이어리를 삭제하는 기능을 구현하였습니다.
> 고민, 과정, 궁금한점
다이어리 디테일 부분에 네비게이션 바가 너무 많다고 생각되면 메뉴로 묶어도 괜찮을 것 같습니다. 저는 별로 상관없는것 같아요
- 여행 삭제
https://user-images.githubusercontent.com/76734067/207232559-3449e324-fb32-4ed9-a4b8-92c178f71bd8.mp4
- 다이어리 삭제
https://user-images.githubusercontent.com/76734067/207232459-c92d9918-cd99-485e-8ed1-7b71a617a9fd.mp4

[삭제 기능] 여행, 다이어리 삭제

---

Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/PlanAddViewControllerDelegate.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/PlanListViewModelDelegate.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift

> 변경사항 간략하게 
- 일정에 변경이 생기면 바로 적용되도록 했습니다. 
- 일정에서 장소가 있다가 사라지면 해당 장소가 삭제 되는 작업이 누락되고 있어서 추가해주었습니다. 
> 고민, 과정, 궁금한점

[다이어리 목록] 일정 변경사항이 바로 적용되도록 변경

---

Doesaegim/Doesaegim/Data/ViewModel/ExpenseInfoViewModel.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarHeaderView.swift
Doesaegim/NSManagedObjectClass/Expense+CoreDataClass.swift

* 지출 목록에  금액 (지출 액수 * 환율) 값으로 표기되도록 변경
* Expense를 수정하면서 지출 액수만 나오던 문제를 해결하였습니다.
* 딱 1줄이면 해결이 되더군요..!

[지출 목록] 지출 목록에  금액 (지출 액수 * 환율) 값으로 표기되도록 변경

---

Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift

> 변경사항 간략하게 
- 스크롤을 빠르게 하는 경우 살짝 끊기는 듯이 업데이트 되어 fetchBatchSize를 40으로 늘렸습니다. 
> 고민, 과정, 궁금한점

refactor: 일정 목록 fetchBatchSize 변경

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/App/Info.plist

> 변경사항 간략하게 
- 앱을 세로모드로 고정했습니다. 
> 고민, 과정, 궁금한점

feat: 세로모드로 고정

---

README.md

> 변경사항 간략하게 
- 뱃지에 링크 추가했습니당~!
> 고민, 과정, 궁금한점

docs: Download on the AppStore 링크 추가
