Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationView.swift
Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/ViewModel/SearchingLocationViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/ViewModel/SearchingLocationViewModelDelegate.swift

- 리뷰 피드백을 반영했습니다! (SearchingLocationViewControllerDelegate -> SearchingLocationViewModelDelegate로 네이밍 변경)
- SearchingLocationView에 있던 searchBarField를 제거한 대신 UISearchController를 도입했습니다.
- 기존의 CompositionalLayout을 직접 생성하는 방식 대신 재훈님이 말씀해주셨던 UICollectionLayoutListConfiguration을 도입했습니다.
- MKLocalSearch 시 메모리 경고가 뜨는 현상을 수정했습니다.
- 결과가 없을 경우 label을 표시하기 위해 선경님이 구현해주신 EmptyLabeledCollectionView를 사용했습니다.
- resolves #12 
- MKLocalSearch.Request를 다루면서 검색 범위를 사용자의 현재 위치 기준으로 해야한다는 생각에 삽질을 좀 많이 한 것 같습니다..😂
- MKLocalSearch.Request의 `region` 프로퍼티에 값을 지정해줌으로써 검색 범위를 좁힐 수 있다고 되어 있지만 저는 반대로 region에 값을 지정해주니 같은 키워드라도 해외 지역의 검색 결과값이 먼저 나타났고, region에 값을 지정해주지 않을 땐 국내 지역의 검색 결과가 우선적으로 나타났습니다. 이런 상황에 대해 검색해봐도 마땅한 답을 찾을 수가 없더라구요..🥲 우선은 값을 지정해줬지만 조금 더 알아봐야할 것 같습니다..ㅜㅜ
- UISearchController를 도입하는 과정에서 검색 결과를 표시하는 …

[장소 추가] UISearchController, UICollectionLayoutListConfiguration 도입

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim.xcodeproj/xcshareddata/xcschemes/Doesaegim.xcscheme
Doesaegim/Doesaegim/Presentation/MainTabBarController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanLocalRepository.swift
Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanRepository.swift
Doesaegim/Doesaegim/Utility/Extensions/UIScrollView+DidPassPoint.swift
Doesaegim/Doesaegim/Utility/Extensions/UIViewController+SetRightBarPlusButton.swift
Doesaegim/NSManagedObjectClass/Plan+CoreDataClass.swift

> 변경사항 간략하게 
- resolves #13, #15
- 일정 추가 화면이랑 연결하는 김에 여행 목록에서 넘어오는 것도 연결했습니다. 
- 코어데이터 호출 방식과 스냅샷 방식을 변경했습니다. 
<br>
> 고민, 과정, 궁금한점
- 데이터가 많을 경우를 대비해 코어데이터를 활용하는 방식을 변경했습니다. 
- 코어데이터에 fetchRequest를 날릴 때 fetchBatchSize를 화면 크기만큼의 일정 개수로 설정해서 일정은 한 번에 모두 가져오되 실제 메모리에 올리는 건 유저의 스크롤 정도에 따라 필요한 만큼만 올리도록 했습니다. 
- 관련해서 스냅샷도 새로 추가된 일정에 관한 데이터만 매번 갱신하는 방식으로 변경했습니다. 
- 좀 더 자세한 설명을 위해 오늘 [기술 공유 발표 자료 링크](https://docs.google.com/presentation/d/1uIOf-sDcI7cQ3BYTGM6BYKKsZm7Wjw0M5hpVmQ80tiE/edit?usp=sharing)를 같이 첨부합니다, 제 나름대로 왜 이런식으로 했는지, 어떤 문제를 겪었는지 슬라이드마다 아래 주석 칸에 설명으로 달아놨습니다! 주말이 끝나기 전에 해당 주제로 기술 포스팅...도 쓰는 게 목표인데 쓰는대로 공유하겠습니다...!
<br>

[일정 목록] 코어데이터 호출 방식 변경 및 여행 목록, 일정 추가 화면과 연결 #13, #15

---

Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
Doesaegim/Doesaegim/Utility/Custom/CustomCalendar.swift
Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift

* 기존에 캘린더에서 헤더부분에 일 단위까지 나오는 부분을 수정했습니다.
* 여행추가가 되지 않는 오류를 해결했습니다.
* 기존에 여행추가시, 여행 제목과 날짜가 올바른지 판단을 뷰컨트롤러에서 했었는데 뷰모델의 역할로 변경해주었습니다.
* 오타를 수정하였습니다.
* @available(*, unavailable) 키워드를 사용하여 비가용성 정의하였습니다.
한 줄 짜리 코드일 때, 함수안에 넣어서 선언하는게 더 좋을지 아니면 그냥 한 줄로 작성해야할지에 대한 고민이 생겼습니다..!
예를들어 네비게이션 타이틀을 변경하는 경우,  viewDidLoad에 `navigationItem.title = "여행 추가"` 한 줄로 작성을 하거나 아니면 `func configureNavigation()` 함수 안에 `navigationItem.title = "여행 추가"`를 작성해주고 viewDidload에 `configureNavigation()` 과 같이 작성하는 방식이 있을 것 같은데, 저는 한 줄로 작성할 수 있으면 한 줄로 작성을 하는 스타일인데, 팀원분들은 어떤 의견이신지 궁금합니다..!
|변경 전|변경 후|
|---|---|
|![IMG_0017](https://user-images.githubusercontent.com/77199797/202901299-a3be814e-d480-4438-921e-cf80d0a6006a.PNG)|![IMG_1536674ED6D9-1](https://user-images.githubusercontent.com/77199797/202901310-e05f4419-45db-4d95-9ba …

[여행추가] 리팩토링 및 버그 수정

---

Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift

> 변경사항 간략하게 
* 기존에 일정 추가 화면에서, 장소를 입력하지 않아도 버튼이 활성화 되었는데, 장소를 입력해야만 버튼이 활성화 되도록 수정하였습니다.
* CoreData에 일정을 추가하는 기능을 구현하였습니다.
> 고민, 과정, 궁금한점
* 일정을 CoreData에 저장할 때, Travel 객체가 필요합니다.
* 여행목록 -> 일정목록 화면으로 이동할 때, Travel에 대한 id만 갖고 있기 때문에, 여행을 추가할 때, Travel fetch를 한 번 더 해서 id 값과 같은 id인 Travel 객체를 반환해오도록 구현을 해야 하나 라는 생각을 했습니다.
* 하지만 여행목록 -> 일정목록으로 이동할 때, id만 넘겨주는 것이 아니라 Travel을 넘겨주면 따로 fetch할 필요가 없을 것이라고 생각했습니다.
* 지금은 여행목록 화면에서 Travel 객체를 사용하는게 아닌 TravelInfoViewModel을 사용하고 있어서 여행목록 -> 일정목록 화면으로 이동할 때, Travel 객체를 넘겨주려면 어쩔 수 없이 Travel에 대해 fetch 후, id 값을 비교해서 Travel 객체를 찾아서 넘겨줘야 하는 상황인 것 같은데, TravelInfoViewModel을 꼭 사용해야하는 있을지 궁금합니다..!
* 일정을 추가하고 pop하게 되면 일정목록 화면이 업데이트 되지가 않네요..!
* 목록부분을 제가 구현하지 않아서 잘은 모르지만 일정을 가져오는 메서드를 `viewWillAppear()` 에서 하면 될 줄알고 시도해봤는데, 안되더라구요..! 어디가 문제인지 한 번 알아봐야 할 것 같아요.
* 화면을 …

[일정 추가] 일정 추가 기능 구현

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/DTO/PersistentDTO/ExpenseDTO.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/Model/ExchangeResponse.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/ExpenseAddPickerViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/ExpenseAddPickerViewProtocol.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListCell.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
Doesaegim/Doesaegim/Utility/Constants.swift
Doesaegim/Doesaegim/Utility/ExpenseType.swift
Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
Doesaegim/NSManagedObjectClass/Expense+CoreDataClass.swift

* 환율 정보를 담고있는 딕셔너리를 선언했습니다.
* #54 
1. 최초에 UserDefault에 환율 정보가 있는지 확인합니다.
2. 환율 정보가 없다면 오늘 날짜를 기준으로 API 요청을 보내서 환율 정보를 받아옵니다. 
1. 오늘 날짜의 환율 정보를 불러올 수 없다면 (오전 12 ~ 10시 사이) API 요청을 보내 어제 날짜의 환율 정보를 불러옵니다.
2. 환율 정보를 불러왔다면 (어제 날짜 기준이든, 오늘 날짜 기준이든) 딕셔너리에 [날짜: 환율정보]의 값을 저장하고 이를 디코딩해서 UserDefault에 저장합니다.
3. 환율 정보가 있다면 UserDefault에서 불러온 데이터를 [날짜: 환율정보] 형식으로 인코딩합니다.
1.  오늘 날짜를 key 값으로 가진 환율정보가 있다면 API 요청을 하지 않고, 불러옵니다.
2. 오늘 날짜를 key 값으로 가진 정보가 없다면, 어제 날짜를 key 값으로 가진 환율 정보를 확인합니다.
3. 있다면 API 요청을 하지 않고 불러옵니다.
4. 오늘 날짜, 어제 날짜를 key 값으로 가진 환율 정보가 없다면 API 요청을 보내도록 돌아갑니다. (2번으로)
* 지출 추가 기능 구현
* 지출 추가시에도 일정 추가와 같이 Travel 객체가 필요하기 때문에 지출 목록에서 받아오도록 구현하였습니다.
* 환율 정보를 하루에 한 번은 갱신하는 캐시를 구현하려다 보니, UserDefault와 사전자료형으로 구현하였는데 더 좋은 방법이 있을까 궁금합니다.. 딕셔너리 대신 NSCache를 사용하는게 더 좋았을까요..?!
* 지출을 추가하고 뒤로 pop 하게 되면 지출 내역 …

[지출 추가] 환율 조회 캐시 구현 및 지출 추가시 CoreData 저장 기능 구현

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/DTO/PersistentDTO/DiaryDTO.swift
Doesaegim/Doesaegim/Data/DTO/TemporaryDiary.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/PlaceSearchButton.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModelDelegate.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/PickerDataSource.swift
Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationView.swift
Doesaegim/Doesaegim/Repository/DiaryScene/DiaryAddLocalRepository.swift
Doesaegim/Doesaegim/Repository/DiaryScene/DiaryAddRepository.swift
Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift
Doesaegim/NSManagedObjectClass/Location+CoreDataClass.swift

> 변경사항 간략하게
- #53 
- #59 
- #66 
- #67
- 여행 텍스트필드를 누르면 커스텀 피커가 뜨고 여행을 선택할 수 있도록 구현했습니다. 
- 장소 버튼을 누르면 보경님이 만들어주신 장소 선택 컨트롤러로 이동후 선택사항을 반영할 수 있도록 구현했습니다. 
- 제목, 내용을 입력할 수 있도록 구현했습니다. 
- 기존에 다이어리 생성 및 추가 시 장소가 누락되고 있어서 해당 부분을 수정했습니다. 
<br>
> 고민, 과정, 궁금한점
- 코멘트로 달겠습니다!
여행 선택 시 텍스트필드에 반영
장소 선택 시 버튼에 반영 
제목/내용 누르면 키보드에 가리지 않도록 위치 이동

[다이어리 작성] 여행, 장소, 제목, 내용 입력

---

Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/ExpenseAddPickerViewController.swift
Doesaegim/Doesaegim/Services/NetworkManager.swift

* 환율 조회 API 오류 수정
* 기존 네트워크 통신 성공 시, completion handler로 처리를 해줬는데, URLSession에 async/await API를 사용하여 리팩토링
* 환율 조회 API가 작동이 안됐던 이유는, UserDefault에 환율 조회 API를 조회한 날짜를 담고 있는데, 그 날짜가 오늘 날짜와 다르면 API 요청을 보내야하는데 보내지 않았습니다..
* async/await을 처음 사용해봤는데, 코드가 깔끔해지고 알아보기 더 쉽다고 느꼈습니다. 또한 클로저로 넘겨주지 않아서 조회 성공시 처리해야할 부분에서 변수를 캡처하지 않는다는 장점도 있는 것 같아요.
* 기존과 동일하기 때문에 스크린샷은 패스하겠습니다!

[환율 조회] 버그 해결 및 네트워크 통신 리팩토링

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CalendarViewController.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendar.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCell.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCellProtocol.swift
Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCellViewModel.swift
Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift

* 여행을 추가할 때, 출발 날짜를 선택하면 출발 날짜 이전은 선택하지 못하도록 구현했습니다.
* 일요일일 때, label Color를 수정했습니다.
* Cell에 String 자료형으로 일자만 갖고있었는데, Date() 자료형으로 수정하였습니다.
* 일정 및 지출 추가시 여행날짜에 포함되지 않으면 선택하지 못하도록 수정하였습니다.
* 선택 못하는 날짜의 색상을 변경하였습니다.
* Cell에서 원래 "1", "2" 와 같이 일자만 들고있고, 달력에서 연도와 달을 가져오는 식으로 구현을 했는데, Date() 형식으로 연도, 달, 날짜 까지 갖고있는데 더 좋다고 생각해서 변경하였습니다.
* 일요일인지 판별하는 것을 Cell에서 해주는 게 맞을지 고민이 됐습니다. ViewController와 ViewModel 처럼 Cell도 CellViewModel을 만들어서 구현을 하였는데, 그냥 Cell에서 해줘도 될지..? 의견이 궁금합니다!

[커스텀 캘린더] 캘린더 기능 추가

---

Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseCollectionHeaderView.swift
Doesaegim/Doesaegim/Utility/CustomGraph/CustomChartItem.swift

- 지출 그래프의 카테고리 별로 데이터가 합쳐서 표시되도록 수정했습니다.
- 그래프 애니메이션과 함께 올리려고 했던 커밋이지만 늦어질 것 같아 미리 올립니다..!
- 다이어리 이미지 목록이 빈배열일 경우 이미지뷰를 히든 처리하도록 수정했습니다.
- 모달창 또는 내비게이션으로 해당 뷰가 푸시되었을 때 모두 빠져나올 수 있도록 처리하는 메서드를 구현했습니다.
- 다이어리 날짜 표시를 단순 description 처리해놓았었는데 DateFormatter를 적용하도록 수정했습니다.
- resolves #104 
- 코멘트로 남기겠습니다!
present로 상세 화면을 띄울 때 나타나는 alert 스크린샷 입니다!!
https://user-images.githubusercontent.com/50136980/204451540-7546d38f-5865-4ba7-ac0b-92fa105524c6.mp4

[리팩토링 및 버그 수정] 다이어리 조회, 그래프 이슈 수정

---

Doesaegim/Doesaegim/Repository/DiaryScene/DiaryAdd/DiaryAddLocalRepository.swift
Doesaegim/NSManagedObjectClass/Plan+CoreDataClass.swift
Doesaegim/NSManagedObjectClass/Travel+CoreDataClass.swift

> 변경사항 간략하게 
- resolves #53 
- 유저 편의를 위해 여행 피커에 종료 날짜가 현재에 가까운 순서대로 뜨도록 변경했습니다. 
> 고민, 과정, 궁금한점

[다이어리 작성] 여행 피커 순서를 종료 날짜 최신순으로 변경 #53

---

Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/CustomPieChart.swift
Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceShapeLayer.swift
Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceTextLayer.swift

- 원형 그래프의 애니메이션을 구현했습니다.
- 지출 데이터가 있을 경우에만 애니메이션이 실행되며, 시계 방향으로 순차적으로 동작합니다.
- 원형 그래프에 표시되는 텍스트의 위치를 조정했습니다.
- #102 
- 애니메이션 구현을 위해 CABasicAnimation의 keyPath를 커스텀 해야할 뻔 했지만 기존에 주어진 keyPath를 최대한 활용해 해결할 수 있었습니다.
- keyPath 중 선을 그리는 애니메이션을 설정할 수 있는 `strokeEnd`를 활용하였고, lineWidth를 원형 차트의 반지름만큼 키워 파이 조각의 면이 채워지는 듯한 효과를 주었습니다.
- 원형 차트의 파이 조각들을 시계 방향 순서로 차례대로 표시하는 과정에서 고민이 많았습니다.
- 이전 파이 조각의 애니메이션이 언제 끝나는 지 확인이 필요해서 `CAAnimationDelegate`를 채택 받아 애니메이션이 끝나는 지점에 다음 파이 조각의 애니메이션이 시작될 것임을 저장하고, setNeedsDisplay()를 실행하여 draw 메서드가 재실행되도록 했습니다.
- 블러 처리되어 있는 경우 애니메이션이 동작하지 않도록 해야했기에 isAnimating 프로퍼티를 별도로 선언해서 draw 메서드 내부에서 분기처리 해두었습니다.
- 텍스트 위치의 경우 텍스트를 표시할 파이 조각이 원형 차트의 중심을 기준으로 왼쪽과 오른쪽 중 어디에 위치해 있는지 계산해 x좌표를 구하도록 했고, y좌표도 마찬가지로 파이 조각이 위와 아래 중 어디에 위치하고 있는지 계산해 값을 조정했습니다. …

[커스텀 그래프] 원형 그래프 애니메이션 구현

---

Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/DiaryListViewModelProtocol.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListCell.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListHeaderView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift

> 변경사항 간략하게 
- 같은 섹션의 내용도 다른 헤더로 분리되는 버그를 수정하였습니다.
- 다이어리를 추가한 후 목록으로 돌아왔을 때 다이어리가 추가되어 있지 않은 버그를 수정하였습니다.
- 다이어리 셀의 이미지가 영역을 넘어서 돌출되는 버그를 수정하였습니다.
- 셀 터치시 첫번째 섹션의 셀로 인식하는 버그를 수정하였습니다.
> 고민, 과정, 궁금한점
> 같은 섹션의 내용도 다른 헤더로 분리되는 버그
- 섹션의 영역을 indexPath.section이 아닌 셀의 indexPath.row로 구분하여 발생한 버그였습니다.
> 다이어리를 추가한 후 목록으로 돌아왔을 때 다이어리가 추가되어 있지 않은 버그
- 다이어리 목록을 패치해오는 과정을 `viewDidLoad`에서 수행하였기 때문에 앱을 실행하면서 단 한번만 패치해오기에 발생한 버그였습니다. 패치 해오는 코드를 `viewWillAppear`로 옮겨 다이어리 목록화면이 나타날때마다 패치하여 해결하였습니다.
> 다이어리 셀의 이미지가 영역을 넘어서 돌출되는 버그
- 다이어리 셀의 `imageView`의 `layer.clipsToBounds`를 `true`로 설정해 이미지 뷰의 `bound`를 넘어가는 컨텐츠는 가리도록 설정하여 해결하였습니다.
> 셀 터치시 첫번째 섹션의 셀로 인식하는 버그
- 세번째 섹션의 첫번째 셀을 누르면, 첫번째 섹션의 첫번째 셀에 대한 다이어리 디테일 화면으로 넘어가는 등, 첫번째 섹션의 셀로만 이동하는 버그가 있었습니다.
- 셀을 섹션으로 구분하지 않고 indexPath.row로만 데이터를 구분해서 발생한 에러였습니다.
- …

[다이어리 목록] 다이어리 목록 버그 수정

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/DetectedFaceCell.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController+CollectionView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/TempMosaicViewController.swift
Doesaegim/Doesaegim/Utility/Extensions/UIImage/UIImage+.swift

> 변경사항 간략하게 
- `scaleAndOrient` 메서드를 `UIImage`익스텐션으로 구현하였습니다.
- 얼굴인식 작업이 여러번 수행되는 버그를 수정하였습니다.
- 셀 선택 액션을 추가하였습니다. 사용자가 선택했다는 것을 알 수 있게끔 구현하였습니다.
- 임시 모자이크 뷰컨트롤러로 데이터를 전송하였습니다.
- 얼굴인식 뷰에 레이블, 네비게이션 타이틀 등 UI요소를 추가하였습니다.
> 고민, 과정, 궁금한점
- 얼굴인식 작업이 여러번 수행되었던 이유는, 얼굴 인식 작업의 시작을 `viewDidLayoutSubviews`메서드에서 수행하였기 때문이였습니다.
- `viewDidLayoutSubviews`는 화면의 frame상에 변화가 있을 때, frame을 지정하기 위해서 호출되는 메서드입니다.
- 한번 얼굴 인식 작업이 완료 -> 컬렉션뷰의 DiffableDataSource가 변화를 탐지 -> `UICollectionView`의 셀을 재구성 -> Frame이 변하므로 `viewDidLayoutSubviews` 재호출... -> 어디선가 연쇄가 끊길 때까지 호출
- 이와같은 문제점이 있어 여러번 수행되었습니다.
- frame도 결정되고, 라이프 사이클에서 뷰가 나타날때마다 한번만 호출되는 `viewDidAppear`메서드 안에 구현하여 버그를 해결하였습니다.
---
- 탐지된 정보를 가지고 있는 `DetectInfoViewModel`에는 `isSelected`라는 선택여부를 가지는 `Bool` 변수가 위치합니다.
- `UICollectionViewDelegate`를 채택하여, 셀을 선택할 때마다 해당 …

[얼굴 인식] 탐지 데이터 뷰컨트롤러 전송, 얼굴 선택 인터렉션

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseChartView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseCollectionHeaderView.swift
Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/BarBackgroundLayer.swift
Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/BarShapeLayer.swift
Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/BarTextLayer.swift
Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/CustomBarChart.swift
Doesaegim/Doesaegim/Utility/CustomGraph/CustomChartItem.swift
Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/CustomPieChart.swift
Doesaegim/Doesaegim/Utility/ExpenseType.swift

> 변경사항 간략하게 
- 날짜를 기준으로 지출 내역을 표시하는 막대 그래프와 애니메이션을 구현했습니다.
- 막대 그래프의 경우 단순 막대와 지출 일자만 표시하기에는 사용자에게 제공되는 정보가 부족할 것이라는 생각이 들어 좌측에 금액 단위를 추가로 표시했습니다.
- 두 차트가 각각 다른 기준으로 데이터를 표현하지만 기존의 `CustomChartItem`를 동일하게 활용하고 싶어 제네릭 타입으로 수정해 리팩토링했습니다.
- `UISegmentedControl`을 도입하여 카테고리별과 날짜별로 보이는 그래프가 다르게 표시되도록 구현했습니다.
- 또한, `UISegmentedControl`의 값이 변경될 때마다 그래프의 애니메이션이 다시 재생되도록 구현했습니다.
- `UISegmentedControl`과 그래프 뷰를 합쳐 별도의 뷰 `ExpenseChartView`로 분리해 컬렉션 헤더뷰의 코드양을 줄였습니다.
- resolves #49
- resolves #102  
> 고민, 과정, 궁금한점
세그먼트 컨트롤의 선택된 인덱스 값이 변경될 때마다 애니메이션이 재생되도록 구현하는 과정에서 약간의 어려움이 있었습니다.
레이어의 애니메이션을 동작시키기 위해서는 애니메이션을 생성하고, 이를 레이어에 추가해주는 과정을 거쳐야 헀는데요,
이러한 상황에서 세그먼트 컨트롤의 값이 변경될 때마다 애니메이션을 생성해 추가해주는 건 **각각의 레이어가 중복된 애니메이션을 여러 개 갖게 되어** 좋지 않다고 생각하기도 했고, 무엇보다 기존에 추가된 서브 레이어들이 이미 밑에 깔려 있어 **애니메이션이 동작하고 있어도 동작하지 않는 …

[커스텀 그래프] 막대 그래프 및 애니메이션 구현

---

Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCellViewModel.swift

* `calendar.component(.weekday, from: date)` 값이 1이면 일요일로 표시되도록 변경했습니다.
* 원래는 `calendar.component(.weekday, from: date)` 값이 2일때 일요일로 표시되도록 구현이 되어있었는데, 분명 구현했을 때는 정상작동을 했었는데, 어디선가 잘못된 점이 더 있을 것 같은데 아직 정확하게 파악이 되지는 않았습니다.. ㅠ 
|수정 전|수정 후|
|---|---|
}![스크린샷 2022-12-01 오전 11 29 32](https://user-images.githubusercontent.com/77199797/204965260-d00f7570-dd8d-4c55-a2de-401c0de869b7.png)|![스크린샷 2022-12-01 오전 11 35 42](https://user-images.githubusercontent.com/77199797/204965018-8998b60b-30e7-4989-b6ad-a75262d5e919.png)|

[커스텀 캘린더] 일요일 날짜 Label이 붉은색으로 나타나지 않는 오류 수정

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseChartView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/CustomBarChart.swift
Doesaegim/Doesaegim/Utility/CustomGraph/CustomChartItem.swift
Doesaegim/Doesaegim/Utility/CustomGraph/CustomChartType.swift
Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/CustomPieChart.swift
Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceShapeLayer.swift
Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceTextLayer.swift

- 파이 차트의 조각 레이어와 텍스트 레이어에서 공통으로 구현되어 있는 프로퍼티들을 차트 자체에서 관리하도록 수정했습니다.
- 파이 차트가 화면에서 보이지 않았다가 다시 보이게 되었을 때 동일한 레이어가 중복으로 쌓이는 문제를 수정했습니다.
- 파이 차트의 텍스트 위치를 최종적으로 조정했습니다. ~~진짜_최종~~
- 지출 추가 후 파이 차트가 갱신되지 않는 문제를 수정했습니다.
- 이전에는 PieceShapeLayer와 PieceTextLayer 클래스로 전체 차트가 그려질 영역값을 받아와 내부에서 각각 center, radius 프로퍼티를 계산하도록 했지만, 비효율적인 과정이라고 생각되어 처음부터 차트 클래스에서 center와 radius 값을 계산해 각 레이어 클래스 생성 인자로 보내도록 수정했습니다.
- 아래의 첫번째 스크린샷을 확인해보면 다른 화면으로 이동했다가 다시 지출 조회 화면으로 돌아왔을 때 색이 물결치는 듯한 효과를 확인할 수 있는데, 처음 진입했을 때 그려졌던 차트 위에 동일한 차트가 다시 쌓여 발생하는 문제였습니다. 
- 애니메이션을 실행하는 메서드인 `executeAnimation`에 기존의 모든 서브레이어를 삭제하는 메서드인 `removeAllLayers`를 추가하고, 이 `executeAnimation`을 `setupData`에 추가함으로써 문제를 해결했습니다.
- 텍스트 위치를 적절하게 조정하기 위해 다음과 같은 계산식을 적용했습니다. (feat. 결국 사용하게 된 삼각함수)
- 중심각 θ를 갖는 부채꼴에서 원의 중심으로부터 0.7 * radius 만큼 떨어져 있는 위치에 텍스트를 …

[커스텀 그래프 리팩토링] 버그 일부 수정 및 리팩토링

---

Doesaegim/Doesaegim/Data/ViewModel/DiaryInfoViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/DiaryListViewModelProtocol.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift
Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift

> 변경사항 간략하게 
- 다이어리 목록에서 헤더와 셀이 매치되지 않는 버그를 수정하였습니다.
> 고민, 과정, 궁금한점
- 딕셔너리의 겨우 삽입한 순서대로 삽입되지 않고, 다이어리 정보를 관리하던 **배열**은 정보를 순서대로 저장했기에 이에 순서정보가 충돌하여서 발생한 버그였습니다. 
- 기존에는 여행의 이름과 디어일 정보를 `[(여행이름 문자열): (여행의 다이어리 정보)]`와 같은 사전정보로 관리하고 있었습니다. 그리고 발견된 여행들마다 몇번째 섹션의 여행 제목은 ~~~이군 과 같은 정보도 사전으로 관리하고 있었습니다. 
- 하지만 사전에 데이터를 특정 순서대로 저장했다고 해도, 조회할때도 순서대로 읽어올 것을 보장하지는 않습니다.
- 다이어리에 대한 정보는 배열에 받아온 순서대로 저장하였습니다.
- 이 사전과 다이어리 배열정보를 같이 읽어오면서 인덱스가 서로의 정보가 아닌점이 문제였습니다.
- 같은 여행의 정보만 담을 수 있으면서 순서도 지켜주는 자료형이 무엇이있을까 고민을 하다가 튜플의 배열을 떠올렸습니다.
- 결국에는 배열이라서 여행정보가 저장되는것과 동일하고, 게다가 튜플의 원소중하나로 다이어리의 정보배열을 넣어주면 다이어리정보배열을 따로 빼서 관리할 필요도 없어집니다.
- 마지막에 여행의 시작일을 기준으로 내림차순으로 정렬해주는 작업만 추가하였습니다.

[다이어리 목록] 다이어리 셀과 헤더가 매칭되지 않는 버그 수정

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Services/FileProcessManager.swift
Doesaegim/Doesaegim/Services/ImageCacheManager.swift

> 변경사항 간략하게 
- 이미지의 메모리 캐시를 구현하고, 이미 캐시에 저장된 이미지일 경우 캐시에 있는 이미지를 사용합니다.
- 조회했던 다이어리를 다시 조회할 경우 이미지를 불러오는 시간을 15배정도 향상시켰습니다.
> 고민, 과정, 궁금한점
캐시 사용 전
캐시 사용 후

[리팩토링] 이미지 메모리캐시 구현

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/ViewModel/SettingOptionViewModel.swift
Doesaegim/Doesaegim/Presentation/SettingScene/SettingViewController.swift
Doesaegim/Doesaegim/Presentation/SettingScene/View/SettingTableViewCell.swift
Doesaegim/Doesaegim/Presentation/SettingScene/View/SettingViewController.swift
Doesaegim/Doesaegim/Presentation/SettingScene/ViewModel/SettingViewModel.swift
Doesaegim/Doesaegim/Presentation/SettingScene/ViewModel/SettingViewModelProtocol.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddView.swift

> 변경사항 간략하게 
- 기본적인 설정 뷰 UI를 작성하였습니다.
- 설정화면에 있는 목록은 다음 세가지 입니다.
1. 날짜/시간 표시
2. 알림설정
3. 라이센스
> 고민, 과정, 궁금한점
- 기존처럼 UICollectionView, Compositional Layout, DiffableDataSource를 사용해야할까?
- 설정화면 셀에 나오는 데이터들이 변하지 않기 때문에 DiffableDataSource를 사용하지 않았습니다.
- Compositional Layout을 작성하게 되었을 때 불필요한 코드들이 많아져 사용하지 않았습니다.
- 설정화면의 셀을 터치했을 때는 크게 두가지 동작을 할것이라 생각했습니다.
- 셀을 터치했을때 해당 내용을 설정할 수 있는 다음 뷰컨트롤러로 이동하는 셀
- 셀 내부에 `UISwitch`가 오른쪽에 존재하는 셀
두가지를 구분하기 위해서 Cell의 Type을 열거형으로 정의하였습니다.
```swift
enum SettingOptionType {
case staticCell(model: SettingOptionViewModel)
case switchCell(model: SettingOptionViewModel)
}
```
각 케이스가 설정 셀을 나타낼 정보를 담은 `SettingOptionViewModel`을 연관값으로 가지고 있습니다.

[설정화면] 설정화면의 기본적인 UI구현

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DetailImageCell.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DetailImageSliderView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/ImageSlider/View/ImageSliderView.swift

> 변경사항 간략하게 
- 다이어리 상세 정보가 로딩되는 동안 ActivityIndicator가 띄워지도록 구현했습니다.
- 다이어리 상세 정보가 로딩되는 동안 보여지는 컬렉션뷰의 배경색을 수정했습니다.
- 이미지 슬라이드 시 이전 페이지의 이미지가 살짝 넘어가 보이는 현상을 수정했습니다.
- 이미지 슬라이드 컬렉션 뷰와 페이지 컨트롤을 별도의 클래스 `ImageSliderView` 로 묶어 분리했습니다.
> 고민, 과정, 궁금한점
- `DiaryDetailView`에서 컬렉션뷰가 차지하는 비중이 매우 커서 컬렉션뷰와 페이지 컨트롤을 묶어 클래스로 관리하면 좋겠다! 라는 생각이 들었고, 결국 `ImageSliderView`를 별도로 분리했습니다.
- 이렇게 `ImageSliderView`를 구현하고 나니 `DiaryAddView`에서 사용하는 이미지 슬라이더와도 상당히 유사한 부분이 많아서 공통적으로 사용할 수 있도록 컬렉션뷰 셀도 함께 구현하려고 했지만... 우선은 컬렉션뷰만 구현하게 되었습니다.
- **다이어리 조회 화면**의 경우 진입 시 파일 시스템 내 이미지 경로 배열을 통해 이미지 데이터를 모두 받아와 화면에는 받아져있는 데이터들을 표시만 하는 방식으로 구현되어 있습니다.
- **다이어리 추가 화면**의 경우 각 셀마다 ImageID와 ItemProvider를 통해 이미지를 받아오는데, 이때 이미지를 완전히 받아오기 전까지는 Progress를 표시하는 방식으로 이해했습니다.
- 이처럼 두 화면에서 이미지를 표시하는 방식에 차이가 있어 두 컬렉션뷰 셀 `DetailImageCell`, …

[리팩토링] 다이어리 상세 조회 리팩토링

---

Doesaegim/Doesaegim/Services/FileProcessManager.swift

> 변경사항 간략하게 
- 대용량 이미지 파일에도 대응할 수 있도록 파일 시스템에 저장할 때 5mb 이하가 될 때까지 압축을 반복하도록 변경했습니다.  
> 고민, 과정, 궁금한점

feat: FileProcessManager에서 이미지 저장 시 압축 방식 변경

---

Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift

* #149 
* 지출 추가시 지출 액수를 억단위 미만까지밖에 입력 못하도록 수정하여 Int overflow 버그 해결
* TextField delegate 메서드를 활용해 구현하였습니다.

[지출 추가] 화폐 단위 입력시 Int overflow로 인해 크래시나는 부분 수정

---

Doesaegim/Doesaegim/Data/PlanListSnapshotData.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/PlanListViewModelDelegate.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/CheckBox.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/DateCollectionHeaderView.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanCollectionViewCell.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanViewModel.swift
Doesaegim/Doesaegim/Utility/Extensions/Date/Date+Formatter.swift
Doesaegim/Doesaegim/Utility/Extensions/UIViewController+SetRightBarPlusButton.swift

> 변경사항 간략하게 
- #173 
- #174
- 일정 상세 화면 추가에 따라 목록에서는 제목과 이름이 한 줄만 나타나고 뒤에 내용은 잘리도록 변경했습니다. 
- 환경 설정에서 날짜/시간 표시 방식을 바꾸면 일정 목록에 바로 반영되도록 했습니다. 
- 환경 설정에 있는 방식으로 날짜 표현을 통일했고 한글은 이탤릭이 안 먹혀서 섹션 헤더의 이탤릭체를 제거했습니다. 
- Date extension에 선언된 기존의 `convertHourToMinuteFormatter(with:)` 메서드가 AM, PM인 경우에도 24시간으로 표시되는 버그를 해결했습니다. 
> 고민, 과정, 궁금한점
이름, 내용 레이블의 길이가 1줄로 변경
- 민석님이 말씀해주신 체크박스 사라지는 버그를 수정했습니다. 
|수정 전|수정 후|
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/81314063/206955177-c31d8a75-41ef-43d9-b535-edf0a875584c.png" width=200>|<img src="https://user-images.githubusercontent.com/81314063/206970426-ad5866ed-9f55-4787-add1-b4262e7d3bff.png" width=200>|
날짜 변경되는 모습
https://user-images.githubusercontent.com/81314063/206955335-68f935b2-0116-422c-a13b-5ed48e195111.mp4

[일정목록] 이름, 내용 줄 수 제한 및 날짜 표시 방식 변경 #173 #174

---

Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpensePlaceholdView.swift

> 변경사항 간략하게 
- 지출 목록 셀이 선택되는 효과를 막았습니다.
- 지출 목록이 비어 있을 때 화면 전체에 블러처리 효과를 표시하도록 수정했습니다.
- resolves #163 
> 고민, 과정, 궁금한점
수정 전 문제가 되었던 버그와 수정 후 모습입니다!
https://user-images.githubusercontent.com/50136980/206959179-4bcf57ed-ac51-46ab-9740-24078996022f.mp4

[지출 목록 조회] 관련 이슈 수정

---

Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/Model/ExchangeData.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift

* #148
* response의 통화코드에 숫자가 포함되어 있다면, 환율에 1/숫자를 곱한 값으로 표현되도록 구현하였습니다.
* 통화 코드에 숫자가 포함되어있다면 1 / 숫자를 곱하는 로직으로 구현하였는데 더 나은 방법이 있을지.. 궁금하네요 ㅠ

[지출 추가] 환율 정보 (일본, 인도네시아) 부정확한 환율 버그 수정

---

Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseSectionHeaderView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift

> 변경사항 간략하게
- 설정화면의 설정 값에 따라 지출 목록의 섹션 헤더 표시 방식이 바뀌도록 수정했습니다.
- 섹션 헤더의 날짜가 제대로 표시되지 않고, 스크롤 할 때도 다르게 표시되는 문제를 수정했습니다.
- resolves #163 
> 고민, 과정, 궁금한점
- 처음에는 지출 목록이 날짜별로 묶이지 않아서 발생한 문제라고 생각하고 삽질할 뻔 했지만 이후 표기 값만 잘못 되었다는 것을 알고 생각보다 빠르게 고칠 수 있었습니다👍
섹션 헤더 오류가 발생했을 때의 스크린샷입니다! 동일한 날짜가 연속해서 표시되고 있고, 스크롤 하면 그 값이 바뀌는 것을 확인할 수 있습니다.
https://user-images.githubusercontent.com/50136980/206999015-29116d12-d4ec-404e-887d-1834216ee831.mp4
아래는 수정 후 섹션 헤더 모습입니다!
https://user-images.githubusercontent.com/50136980/207034072-1c2cb4bc-e561-4b9c-98fb-6d85a6dbffef.mp4

[지출 목록 조회] 섹션 헤더 버그 수정 및 설정 화면의 날짜 표시 방식 반영

---

Doesaegim/Doesaegim/Data/DTO/PersistentDTO/DiaryDTO.swift
Doesaegim/Doesaegim/Data/DTO/TemporaryDiary.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModelDelegate.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryEdit/ViewModel/DiaryEditViewModel.swift
Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift

> 변경사항 간략하게 
- #171
- 다이어리 작성 시 장소 입력을 선택적으로 할 수 있도록 변경했습니다. 
- 다이어리 추가/수정 시에 다이어리의 기존 날짜가 새로 선택한 여행의 기간을 벗어나는 경우를 처리했습니다. 
- 생각도 못하고 있다가 민석님이 말씀해주셔서 기간을 벗어나는 경우 기존 선택한 날짜를 nil로 변경하도록 했습니다. 
- 다이어리 디테일 화면에 제목 레이블을 추가했습니다. 
장소 없이 다이어리 추가 
https://user-images.githubusercontent.com/81314063/207045215-37ada8d6-1f75-475f-8a90-eccfeb74ec5c.mp4
여행 변경에 따라 날짜가 여행 기간을 벗어나는 경우 날짜 초기화 
https://user-images.githubusercontent.com/81314063/207045657-1b320e3d-6988-4848-8b3a-0676ef7b3cfc.mp4
다이어리 제목 레이블 추가

[다이어리 편집] 편집 관련 기능 개선

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Data/ViewModel/DetectInfoViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryPhotoDetail/DiaryPhotoDetailViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/FaceDetectViewModelProtocol.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/BlurredImageViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/ViewModel/BlurredImageViewModel.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/ViewModel/FaceDetectViewModel.swift
Doesaegim/Doesaegim/Utility/Extensions/UIImage/UIImage+Downsample.swift

> 변경사항 간략하게 
- #155
- 블러처리할 얼굴을 선택하지 않는 경우 사진이 뜨지 않는 버그를 해결했습니다. 
- 처리할 얼굴의 개수가 증가할 때 이미지 크기가 클수록 시간이 오래 걸리는 문제를 해결하기 위해 다운샘플링을 구현했습니다. 
- 다이어리 디테일 화면부터 다운샘플링을 적용하면 메모리 절약 효과가 클 것 같아 디테일 화면에서부터 쭉 적용했습니다. 디테일 화면 기준 약 50%가량 절약되는 것 같습니다. 
- 얼굴인식 화면의 경우 다운샘플링에 따른 화질 저하로 얼굴 인식률이 줄어드는 문제가 있어 적용하지 않았습니다. 
- 블로그...정리해서 빨리...공유하겠습니다...
> 고민, 과정, 궁금한점
https://user-images.githubusercontent.com/81314063/207130305-7d74c494-3447-4302-875c-0cc852c3e784.MP4

[얼굴 인식] 블러 처리 버그 해결 및 기능 개선 #155

---

Doesaegim/Doesaegim.xcodeproj/project.pbxproj
Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListCell.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ExpenseListViewModelProtocol.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseCollectionHeaderView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListCell.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseSectionHeaderView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelCollectionViewCell.swift
Doesaegim/Doesaegim/Presentation/SettingScene/Library/View/LibraryCollectionViewCell.swift
Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelCollectionViewCell.swift
Doesaegim/Doesaegim/Utility/Extensions/UICollectionViewCell+Shadow.swift

> 변경사항 간략하게 
- 지출 셀의 디자인을 적용하였습니다.
- 지출 헤더의 디자인을 적용하였습니다.
- 지출 삭제기능을 추가하였습니다.
- 컬렉션뷰의 스크롤이 끝에 위치하도록 조정
> 고민, 과정, 궁금한점
- 삭제기능을 구현하면서, 삭제처리가 될 핸들러를 cell 클래스의 메서드에 클로저로 전달하였습니다. 그런데 매번 데이터가 리로드 될 때마다 CellRegister 클래스가 비동기로 처리되는지, 도중에 등록했던 핸들러가 바뀌는 것을 보고 셀에 핸들러 프로퍼티를 만들고 셀의 프로퍼티에 직접 핸들러를 삽입해주는 방식으로 해결하였습니다.
https://user-images.githubusercontent.com/76734067/207225045-f83a44bc-0fcd-4ee6-87ae-713d30623470.mp4

[지출 목록] 지출 셀, 헤더 디자인, 삭제기능 추가

---

Doesaegim/Doesaegim/Repository/TravelScene/SearchingLocation/SearchingLocationRemoteRepository.swift

> 변경사항 간략하게 
- 검색 결과가 없는 상황과 검색에 실패한 상황이 구분되지 않는 문제를 수정했습니다.
> 고민, 과정, 궁금한점
- 문제는 검색 결과가 없는 상황도 에러로 취급하는 `MKError`와, 에러가 발생하면 무조건 실패로 처리하도록 로직을 작성해둔 것이 콜라보를 일으켜 발생한 것이었읍니다... 다음은 MKError.Code의 케이스를 나타내고 있는데, 이 중 검색 결과가 없을 때 `placemarkNotFound` 라는 에러 코드를 반환하게 됩니다.
```objective-c
enum MKErrorCode {
MKErrorUnknown = 1,
MKErrorServerFailure,
MKErrorLoadingThrottled,
MKErrorPlacemarkNotFound,
};
```
- 이를 수정하기 위해 같은 에러라도 placemarkNotFound일 경우는 요청 성공 처리하고, 빈배열을 보내도록 수정했습니다.
- 그렇지만 에러가 발생했음에도 성공 처리하는 건 마음에 좀 걸리네요..😞
동일한 상황에서 버그 수정 전과 후의 모습입니다!
https://user-images.githubusercontent.com/50136980/207228091-16c8e403-218c-423e-b9d2-37c94ad39e48.mp4
https://user-images.githubusercontent.com/50136980/207226337-317498f3-540f-4476-bcf9-7888b36ccb10.mp4

[장소 검색] 검색 결과가 없을 때 검색 실패 alert이 뜨는 현상 수정

---

Doesaegim/Doesaegim/App/Doesaegim.xcdatamodeld/Doesaegim.xcdatamodel/contents
Doesaegim/Doesaegim/Data/DTO/PersistentDTO/ExpenseDTO.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddView.swift
Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
Doesaegim/Doesaegim/Repository/ExpenseScene/ExpenseAdd/ExpenseAddLocalRepository.swift
Doesaegim/Doesaegim/Repository/ExpenseScene/ExpenseAdd/ExpenseAddRepository.swift
Doesaegim/NSManagedObjectClass/Expense+CoreDataClass.swift

* 지출 상세화면을 구현하였습니다.
* 지출 수정기능을 구현하였습니다.
* 최대 지출 입력금액을 9자리에서 7자리로 줄였습니다.
* 지출을 추가할 때, cost 프로퍼티 하나만 가지고는 상세보기에서 지출액수를 표시할 수 없어 지출을 추가할 때, 환율도 입력받을 수 있도록 Expense 객체를 수정하였습니다.
* 지출목록 셀에서 cost로 금액을 보여주고 있던 것을 cost * 환율로 수정해야합니다.
* 재훈님께서 지출목록화면을 업데이트 해주셔서 머지가 된 후 수정하겠습니다.

[지출 수정] 지출 상세화면 및 수정 기능 구현

---

Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/BarTextLayer.swift
Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/CustomPieChart.swift

> 변경사항 간략하게 
- 민석님이 알려주신 특정 상황에서 파이차트가 그려지지 않는 문제를 수정했습니다.
- 막대 차트의 좌측 금액 단위를 잘라 표시하지 않도록 수정했습니다.
> 고민, 과정, 궁금한점
- 파이 차트의 애니메이션은 원래 다음과 같은 방식으로 동작했습니다.
1. 파이차트는 식비, 교통비, 숙박비, 관광비, 기타의 고정된 순서로 그려집니다.
2. draw 메서드가 실행되면 지출 내역 중 제일 먼저 그려져야하는 지출 타입을 찾아 적절하게 파이 조각을 만들어 이를 애니메이션과 함께 그립니다.
3. 첫번째 파이조각의 애니메이션이 끝나면 `CAAnimationDelegate`의 `animationDidStop`이 실행됩니다.
4. 다음으로 그려야할 지출 타입이 있다면 다음 순서를 저장하고, setNeedsDisplay를 통해 draw 메서드를 재실행합니다.
5. 더 이상 그릴 파이 조각이 없다면 그대로 종료합니다.
- 이 과정이 대체 뭐가 문제인가!! 하고 열심히 찾아본 결과, 테스트 했을 때 식비가 전체 비율 중 매우 작은 부분을 차지하고, 이를 각도로 반환했을 때 0.13도라는 결과가 나왔습니다. 정확한 이유는 알 수 없지만 이렇게 첫번째 조각이 그려진 후 4번 과정의 setNeedsDisplay가 실행되지 않았고, 이후 큰 비중을 차지하는 파이 조각이 그려지지 않아 전체 그래프가 그려지지 않는 것처럼 보였던 것 같습니다..
- 파이 한 조각을 그리는 부분을 별도 메서드(drawOnePiece)로 구현에 두었기에, 4번 과정의 setNeedsDisplay를 drawOnePiece 메서드로 …

[커스텀 그래프] 버그 수정

---

Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/BlurredImageViewController.swift
Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/ViewModel/BlurredImageViewModel.swift

> 변경사항 간략하게 
- 블러 처리 뷰에서 공유하기 버튼이 누락되던 문제를 해결했습니다. 
- 이미지가 있을때만 버튼을 나타내고 싶어서 guard문을 썼었는데 블러처리를 백그라운드 스레드에 async로 보내면서 처리된 이미지를 전달받기 전에 버튼이 초기화되는 문제였습니다...
> 고민, 과정, 궁금한점
https://user-images.githubusercontent.com/81314063/207603150-10e31014-dbaa-4628-baf5-8f0b9ca39498.MP4

hotfix: 블러처리 뷰에서 공유하기 버튼 누락 문제 해결
